apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bar
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'bar'
    server: '*'
  sourceRepos:
  - '*'
