apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  scopes: '[groups]'
  policy.default: ""
  policy.csv: |
    g, 82490324-9599-4264-8464-f8207af98993, role:admin
    g, 212b1d17-e49d-40f3-a47d-6cb4d4a5c64d, role:readonly
